### ISSUE TITLE
state['distribution'] update

### ISSUE THREAD

**Issue by akhanss** [qychen13/DifficultyAwareEmbedding#1]
Dear @qychen13 
Thanks a lot for developing a nice algorithm and for providing a great repo as well. However, I have a question.
As per the algorithm described in the paper, distribution should be updated at the end of each epoch, but I didn't find its reflection in the code. Perhaps I am missing something.
Could you please refer to the code snippet where you update the distribution at the end of an epoch?

Cheers,
Azam.

**Comment by qychen13** [comment]
You are welcome to reach out!

The distribution is updated at the end of training one complementary network. It is not updated at the end of each training epoch. Please refer to the paper for more detailed information. In the released code ,updating weight is implemented at  ada_train(self, maxepoch) function at  utils/engine.py. In this way, you just pass the trained complementary network of iteration $t$ and continue training another complementary network of iteration $t+1$. See the sampled training script, scripts/trainval_resnet50.sh

Best
